ASP.NET_Db4o/Controllers/DataController.cs
using ASP.NET_Db4o.Models;
using ASP.NET_Db4o.Services;
using ASP.NET_Db4o.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP.NET_Db4o.Controllers
{
    public class DataController : Controller
    {
        private readonly IDatabaseService _databaseService;
        private readonly JsTreeService _jsTreeService;
        public DataController()
        {
            _databaseService = new DatabaseService("przykladowa");
            _jsTreeService = new JsTreeService(_databaseService);
        }
        // GET: Data
        public ActionResult ViewTree(string name, string unit)
        {
            return View("StoredListTree", new StViewModel() { name = name, unit = unit });
        }
        [HttpPost]
        public ActionResult AddStoredList()
        {
            var name = Request["Name"];
            var unit = Request["Unit"];
            double quantity = Convert.ToDouble(Request["Quantity"]);
            _databaseService.AddStoredList(new StoredList()
            {
                Name = name,
                MesureUnit = unit
            });
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddToStoredList(EditStoredListViewModel editStoredListViewModel)
        {
            var name = Request["Name"];
            var unit = Request["Unit"];
            double quantity = Convert.ToDouble(Request["Quantity"]);
            _databaseService.AddStoredList(new StoredList()
            {
                Name = name,
                MesureUnit = unit
            });
            _databaseService.AddElementToStoredList(new StoredList()
            {
                Name = editStoredListViewModel.ChildName,
                MesureUnit = editStoredListViewModel.ChildUnit
            }, new StoredList()
            {
                Name = name,
                MesureUnit = unit
            }, quantity);
            return View("StoredListEdit", editStoredListViewModel);
        }
        public ActionResult EditStoredList(string childName, string childUnit, string parentName, string parentUnit, string childValue)
        {
            return View("StoredListEdit", new EditStoredListViewModel()
            {
                ChildName = childName,
                ChildUnit = childUnit,
                ParentName = parentName,
                ParentUnit = parentUnit,
                ChildValue = childValue
            });
        }
        [HttpPost]
        public ActionResult ChalangeUnit(ChalangeUnitViewModel chalangeUnitViewModel)
        {
            Console.WriteLine(_databaseService.ChalangeMesureUnit(new StoredList()
            {
                Name = chalangeUnitViewModel.ChildName,
                MesureUnit = chalangeUnitViewModel.ChildUnit
            }, chalangeUnitViewModel.NewUnit));

            return View("StoredListEdit",
                new EditStoredListViewModel()
                {
                    ChildName = chalangeUnitViewModel.ChildName,
                    ChildUnit = chalangeUnitViewModel.NewUnit,
                    ParentName = chalangeUnitViewModel.ParentName,
                    ParentUnit = chalangeUnitViewModel.ParentName,
                    ChildValue = chalangeUnitViewModel.ChildValue
                });
        }
        public ActionResult DeleteFromStoredList(string name, string unit, string parentN, string parentU)
        {
            _databaseService.RemoveElementFromList(new StoredList() { Name = parentN, MesureUnit = parentU },
                new StoredList() { Name = name, MesureUnit = unit });

            return RedirectToAction("Index");
        }
        public ActionResult DeleteStoredList(string name, string unit)
        {
            _databaseService.RemoveStoredList(new StoredList() { Name = name, MesureUnit = unit });

            return RedirectToAction("Index");
        }

        public ActionResult ChalangeQuantity(EditStoredListViewModel editStoredListViewModel)
        {
            var quantity = Convert.ToDouble(Request["Quantity"]);
            _databaseService.ChalangeElementValue(new StoredList()
            {
                Name = editStoredListViewModel.ParentName,
                MesureUnit = editStoredListViewModel.ParentUnit,
            }, new StoredList()
            {
                Name = editStoredListViewModel.ChildName,
                MesureUnit = editStoredListViewModel.ChildUnit
            }, quantity);
            editStoredListViewModel.ChildValue = quantity.ToString();
            return View("StoredListEdit", editStoredListViewModel);
        }
        public JsonResult GetJsTree3Data(string name, string unit)
        {
            return Json(_jsTreeService
                .GetJsTree3Node(new StoredList() { Name = name, MesureUnit = unit }),
                JsonRequestBehavior.AllowGet);
        }

        // GET: Data
        public ActionResult Index()
        {
            Dictionary<StoredList, Dictionary<string, double>> d = new Dictionary<StoredList, Dictionary<string, double>>();
            foreach (var item in _databaseService.GetStoredListColl())
            {
                _databaseService.order(item);
                d.Add(item, _databaseService.List);
            }
            return View(new OrderViewModel() { List = d });
        }
    }
}

ASP.NET_Db4o/Views/Data/Index.cshtml
@model ASP.NET_Db4o.ViewModels.OrderViewModel
<ul>
    @foreach (var item in Model.List)
    {
        <li class="well">
            @item.Key.Name  @item.Key.MesureUnit
            @Html.ActionLink("Edytuj", "ViewTree", new { name = item.Key.Name, unit = item.Key.MesureUnit }, null)
        </li>
        <text>Potrzeba</text>
    foreach (var dict in item.Value)
    {
            <li>
                @dict.Key @dict.Value
            </li>
        }
    }
</ul>
<h3>
    @using (Html.BeginForm("AddStoredList", "Data", FormMethod.Post))
    {
        <h4>Name @Html.TextBox("Name")</h4>
        <h4>Unit Mesure @Html.TextBox("Unit")</h4>
        <h4>Quantity @Html.TextBox("Quantity")</h4>
        <button class="btn btn-primary">Dodaj</button>
    }
</h3>

ASP.NET_Db4o/Views/Data/StoredListEdit.cshtml
@model ASP.NET_Db4o.ViewModels.EditStoredListViewModel
<h2>
    @Model.ChildName
    <a href="@Url.Action("DeleteStoredList", "Data", new { name = Model.ChildName, unit = Model.ChildUnit }, null)">
        <i class="fa fa-times">
        </i>
    </a>
   @Html.ActionLink("Usun z listy","DeleteFromStoredList", "Data", new { name = Model.ChildName, unit = Model.ChildUnit,parentN= Model.ParentName,parentU =Model.ParentUnit  }, null)
</h2>
<h1>
    @using (Html.BeginForm("ChalangeUnit", "Data", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.ChildName);
        @Html.HiddenFor(x => x.ChildValue);
        @Html.HiddenFor(x => x.ParentName);
        @Html.HiddenFor(x => x.ParentUnit);
        @Html.HiddenFor(x => x.ChildUnit);
        <span>
            Liczone w @Html.TextBox("NewUnit", Model.ChildUnit)
        </span>
        <button class="btn btn-primary">Zmien</button>
    }
    @using (Html.BeginForm("ChalangeQuantity", "Data", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.ChildName);
        @Html.HiddenFor(x => x.ChildUnit);
        @Html.HiddenFor(x => x.ChildValue);
        @Html.HiddenFor(x => x.ParentName);
        @Html.HiddenFor(x => x.ParentUnit);
        <span>
            Liczebność @Html.TextBox("Quantity",Model.ChildValue)
        </span>
        <button class="btn btn-primary">Zmien</button>
    }
</h1>
<h3>
    @using (Html.BeginForm("AddToStoredList", "Data", FormMethod.Post))
    {
        @Html.HiddenFor(x => x.ChildName);
        @Html.HiddenFor(x => x.ParentName);
        @Html.HiddenFor(x => x.ParentUnit);
        @Html.HiddenFor(x => x.ChildUnit);
        @Html.HiddenFor(x => x.ChildValue);

        <h4>Name @Html.TextBox("Name")</h4>
        <h4>Unit Mesure @Html.TextBox("Unit")</h4>
        <h4>Quantity @Html.TextBox("Quantity")</h4>
        <button class="btn btn-primary">Dodaj</button>
    }
</h3>
<text>Parent name: @Model.ParentName, Parent unit: @Model.ParentUnit</text>

ASP.NET_Db4o/Views/Data/StoredListTree.cshtml
@model ASP.NET_Db4o.ViewModels.StViewModel

<script>
    $(document).ready(function () {
        $('#container').jstree({
            'core': {
                'data': {
                    'url': '/Data/GetJsTree3Data?name=@Model.name&unit=@Model.unit',
                    'dataType': 'json'
                }
            }
        });
        $('#container').on('select_node.jstree', function (e, data) {
            var childName = data.node.text.split(' ')[0];
            var childUnit = data.node.text.split(' ')[1];
            var childValue = data.node.text.split(' ')[2];
            var parentName = data.node.parent.split(' ')[0];
            var parentUnit = data.node.parent.split(' ')[1];
            var parentValue = data.node.parent.split(' ')[2];

            console.log(childName);
            console.log(childUnit);
            console.log(childValue);
            console.log(parentName);
            console.log(parentUnit);
            console.log(parentValue);
            window.location.href =
                "http://localhost:2258/data/EditStoredList?childName=" + childName +
                "&childUnit=" + childUnit +
                "&ParentName=" + parentName +
                "&ParentUnit=" + parentUnit +
                "&ChildValue=" + childValue;
        });
    });
</script>

<div id="container"></div>